apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasadailyservice-deployment
  labels: 
    app: nasadailyservice
  namespace: nasadailyservice
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nasadailyservice
  template:
    metadata:
      labels:
        app: nasadailyservice
    spec:
      containers:
      - name: nasadailyservice
        image: adamlang/nasa_daily_service
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nasadailyservice-service
  namespace: nasadailyservice
spec:
  selector:
    app: nasadailyservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080